#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'models'
  description: 'Tailormap API models has all the models for the Tailormap API.'
  version: '1.0'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'

# none; specified in tailormap-api.yaml
servers: [ ]
# none; specified in tailormap-api.yaml
paths: { }

components:
  schemas:
    CoordinateReferenceSystem:
      description: '
      Well-known and client-supported EPSG code.
      Currently Rijksdriehoek/WGS84, new/TODO Web Mercator.
      '
      type: object
      properties:
        code:
          description: 'the EPSG code'
          type: string
          default: 'EPSG:28992'
        definition:
          description: 'PROJ4 string'
          type: string
          default: '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs'
        bounds:
          description: 'Area of validity of this CRS'
          $ref: '#/components/schemas/Bounds'
          nullable: true
          default:
            miny: 646.36
            minx: 308975.28
            maxy: 276050.82
            maxx: 636456.31
      required:
        - code
        - definition
      example:
        code: 'EPSG:28992'
        definition: '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs'
        bounds: {
          miny: 646.36,
          minx: 308975.28,
          maxy: 276050.82,
          maxx: 636456.31
        }

    Bounds:
      description: 'Describes an extent within a Coordinate Reference System'
      type: object
      properties:
        miny:
          description: 'lower bottom'
          type: number
          format: double
        minx:
          description: 'lower left'
          type: number
          format: double
        maxy:
          description: 'upper top'
          type: number
          format: double
        maxx:
          description: 'upper right'
          type: number
          format: double
        crs:
          description: '(EPSG) code of the projection'
          type: string
          nullable: true
      required:
        - miny
        - minx
        - maxy
        - maxx
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000
        crs: 'EPSG:28992'


    AppLayer:
      description: '
      A map layer, but only enough information to draw the layer.
      For advanced functionality that required access to attributes the LayerDetails should be requested.
      '
      type: object
      properties:
        id:
          type: integer
          format: int64
        layerName:
          description: Layer name as known by the service.
          type: string
        title:
          description: Layer title or display name.
          type: string
        serviceId:
          description: A reference to a Service id.
          type: integer
          format: int64
        visible:
          type: boolean
        minScale:
          description: Minimum scale at which this layer should be shown or is not blank. When absent there is no minimum. As reported by the service (ScaleHint or MinScaleDenominator).
          type: number
          format: double
        maxScale:
          description: Maximum scale denominator at which this layer should be shown or is not blank. When absent there is no maximum. As reported by the service (ScaleHint or MaxScaleDenominator).
          type: number
          format: double
        legendImageUrl:
          description: URL to an image with the layer legend.
          type: string
        hiDpiMode:
          type: string
          description: 'For tiled services only'
          enum:
            - disabled
            - showNextZoomLevel
            - substituteLayerShowNextZoomLevel
            - substituteLayerTilePixelRatioOnly
        hiDpiSubstituteLayer:
          description: 'The layer name of this service to substitute when the device pixel ratio is higher'
          type: string
        hasAttributes:
          description: 'Whether this layer has attributes that can be accessed eg. for feature info or attribute list'
          type: boolean
      required:
        - id
        - layerName
        - title
        - serviceId
        - visible
        - hasAtributes

    LayerTreeNode:
      description: Grouping of layers in a tree structure.
      type: object
      properties:
        id:
          description: A unique identifier across all tree nodes.
          type: string
        appLayerId:
          type: integer
        root:
          description: Only a single node in a tree will have this set to true.
          type: boolean
        name:
          description: Display name of this tree node. If appLayerId is present, this is the title of that AppLayer.
          type: string
        description:
          description: Description for this node entered by application admin.
          type: string
        childrenIds:
          description: Ordered list of ids of LayerTreeNodes that are children of this node.
          type: array
          items:
            type: string
      required:
        - id
        - name

    LayerDetails:
      description: 'All details of an app layer.'
      type: object
      properties: # TODO aanvullen
        id:
          type: integer
          format: int64
          readOnly: true
        featureTypeName:
          type: string
        serviceId:
          type: integer
          format: int64
          readOnly: true
        geometryAttribute:
          type: string
        geometryAttributeIndex:
          description: 'index of the geometryAttribute in the array of attributes.'
          type: integer
          format: int32
        geometryType:
          description: '(editable) geometry type of this layer.
        We can have multiple geometry attributes in a layer, but only one is rendered and
        optionally editable) see also see also: nl.tailormap.viewer.config.services.AttributeDescriptor'
          type: string
          enum:
            - 'linestring'
            - 'multilinestring'
            - 'point'
            - 'multipoint'
            - 'polygon'
            - 'multipolygon'
            - 'geometry'
        editable:
          type: boolean
          default: false
        metadata:
          type: string
          nullable: true
        relations:
          title: 'layerDetailsRelations'
          type: array
          minLength: 0
          items:
            type: object
            properties:
              featureType:
                type: integer
                format: int64
              foreignFeatureType:
                type: integer
                format: int64
              type:
                type: string
                enum:
                  - 'relate'
                  - 'join'
        attributes:
          description: '
          Array with attributes.
          **note** that the ordering of this array is determined in the backend and does not need
          to coincide with the actual data in the data source.
          '
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
      required:
        - id
        - serviceId

    Attribute:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        featureType:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        alias:
          type: string
        longname:
          description: 'has featuretype name and name combined with a dot.'
          example: 'v_factsheet_terrein_info.b_minhuur'
          type: string
        editAlias:
          type: string
        type:
          description: 'data type. eg "date" or "string".
          see also: nl.tailormap.viewer.config.services.AttributeDescriptor'
          type: string
          enum:
            - 'date'
            - 'timestamp'
            - 'string'
            - 'double'
            - 'integer'
            - 'boolean'
            - 'linestring'
            - 'multilinestring'
            - 'point'
            - 'multipoint'
            - 'polygon'
            - 'multipolygon'
            - 'geometry'
        visible:
          type: boolean
        selectable:
          type: boolean
        filterable:
          type: boolean
        folder_label:
          type: string
        # editing: TODO needs work / ook integratie met feature API
        editable:
          type: boolean
        defaultValue:
          type: string
        disallowNullValue:
          type: boolean
        disableUserEdit:
          type: boolean
        allowValueListOnly:
          type: boolean
        automaticValue:
          type: boolean
        valueList:
          type: string
          example: 'static'
        editValues:
          type: array
          items:
            type: string

    Feature:
      description: '
      A possibly complete feature from the attribute source. 
      The feature could have been filtered to not provide certain attributes.
      Any geometry attributes will be presented in WKT format
      '
      type: object
      required:
        - __fid
        - attributes
      properties:
        __fid:
          description: 'feature id, a non-mutable identifier from the attribute source'
          readOnly: true
          type: string
        geometry:
          description: '
            Default geometry of the feature as WKT, possibly simplified. 
            Always linearized to make sure that it only holds a specification valid WKT.
            Can be used for highlighting or buffer/selection, not for editing.
            '
          type: string
        attributes:
          description: 'feature attributes in key/value pairs'
          type: object
          minItems: 1
          additionalProperties: true
      example:
        __fid: 1
        geometry: "POLYGON(...)"
        attributes:
          name: "Utrecht"
          geom: "POLYGON(...)"
          surface: 40

    ColumnMetadata:
      type: object
      description: 'presentation metadata for a feature'
      properties:
        key:
          type: string
        alias:
          type: string
          nullable: true
        type:
          description: 'data type. eg "date" or "string".
          see also: nl.tailormap.viewer.config.services.AttributeDescriptor'
          type: string
          enum:
            - 'date'
            - 'timestamp'
            - 'string'
            - 'double'
            - 'integer'
            - 'boolean'
            - 'geometry'
      example:
        key: 'geom'
        alias: 'Geometry'
        type: 'geometry'

    Service:
      description: 'A service provides one or more appLayers'
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: false
        url:
          type: string
          nullable: false
        useProxy:
          type: boolean
          default: false
        styleLibraries:
          type: object
        serverType:
          type: string
          nullable: false
          enum:
            - auto
            - disabled
            - geoserver
            - mapserver
        tilingDisabled:
          type: boolean
        tilingGutter:
          type: integer
        protocol:
          type: string
          enum:
            - tiled
            - wms
            - arcgis
        tilingProtocol:
          type: string
          enum:
            - WMTS
            - TMS
        capabilities:
          description: 'capabilities document of the service - currently only for WMTS'
          type: string
          nullable: true
      required:
        - id

    Component:
      description: 'a component to be used in the application'
      type: object
      properties:
        type:
          description: 'component type eg. featurereport or print'
          type: string
          nullable: false
        config:
          description: 'component specific configuration'
          title: 'componentConfig'
          type: object
          required: [ "enabled" ]
          properties:
            enabled:
              type: boolean
          additionalProperties:
            description: 'anything else, component specific'
            type: object
      required:
        - type
        - config
      example:
        type: 'featurereport'
        config: { template: 'FeatureReport.xsl',
                  legendLayers: [ ],
                  numOfRelatedFeatures: 10,
                  reportLayers: [ ],
                  label: '',
                  title: 'FeatureReport',
                  subTitle: 'detail about parcel $1',
                  layers: [ ] }
